### ISSUE TITLE
UI Settings changes services/AUTOMATIC1111/config.json file

### ISSUE THREAD

**Issue by DevilaN** [AbdBarho/stable-diffusion-webui-docker#102]
**Describe the bug**
Because of volume entry:
```- ./services/AUTOMATIC1111/config.json:/stable-diffusion-webui/config.json```
Each time there is a config change in settings from UI this very file is saved and modified also on local directory.
Above bind mounting file prevents *simple updating* of repository by `git pull` because of conflicting changes in remote and local file.

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   services/AUTOMATIC1111/config.json

no changes added to commit (use "git add" and/or "git commit -a")
```

**Which UI**

auto & auto-cpu

**Steps to Reproduce**
1. Go to 'Settings' tab
2. Change any option
3. Click 'Apply settings' button
4. `git status` in repo directory.

**Hardware / Software:**
Does not matter

**Additional context**
It seems that using bind mount has been a way to share UI configuration between CPU and GPU services (are there people that constantly switching between cpu and gpu versions back and forth worrying about persistent settings)?.
Maybe there was a need for editing it locally for some unknown reason (good for developer, but it can be accomplished by using docker-compose.override.yml so there is no need to bother regular users with that changes).

**Comment by AbdBarho** [comment]
@DevilaN that is a valid problem.

The reason we mount the file in the container is to persist the settings, so when you run again, all changes are still there.

I am not sure what other alternative we have here....

If your problem is only with the the pulling from the repo, you can try
```
git fetch
git reset --hard origin/master
```
or if you want to keep your changes:
```
git stash
git pull
git stash apply
```

**Comment by DevilaN** [comment]
I do not want to propose overcomplicated solutions for simple problems, but I really do appreciate if something is working out of the box without unnecessary digging into internals or requiring some "magic stuff" to be done. That is why docker solution has been my first and only choice. Most of the time it is bulletproof or can be made that.

Preserving configuration between updates and not conflicting with git pull can be achieved using additional volume (local with gitignore for directory contents or anonymous one). Responsibility for creating `config.json` if it does not exists in first place inside volume and place proper link to it inside original location of `config.json` file, can be placed on entrypoint script.

I will gladly prepare solution and create PR if you wish so.

**Comment by AbdBarho** [comment]
Ideally, we should not manually create `config.json` file, it should be created and managed by the UI itself. We only need some overrides, which get applied to the config whenever needed.

I don't think this is easily achievable without tweaking the UI code itself, that being said, I think your proposal for the entrypoint is the right one:
* have a some sort of `override.json` file, which contains all the stuff we need to control (like mounts / paths / etc.) that is part of this repo and is updated when needed.
* in the entrypoint, if a `config.json` already exists in our volume, apply our overrides by merging both jsons back into the config file, something like `jq '. * input' config.json override.json`
* otherwise, just copy the `override.json` to the correct path.


This will ensure, that in case the UI adds new config that requires changes from our side, we can always update the `override.json` without breaking the git pull.

@DevilaN what do you think of this solution?

**Comment by DevilaN** [comment]
Seems like a good direction.

Could you provide example `override.json` or at last state which config values should be overriden so I could prepare working solution and test it?

**Comment by AbdBarho** [comment]
@DevilaN Thank you for wanting to contribute!

These are the overrides: https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/9af4a23ec4eaefbcb98e2a58ac1fd9a04137ecbc/services/AUTOMATIC1111/config.json#L2-L10

**Comment by AbdBarho** [comment]
the config file has been moved to `data/config/auto`
