### ISSUE TITLE
auto: Fails to start with  strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by loglob** [AbdBarho/stable-diffusion-webui-docker#158]
When starting the AUTOMATIC1111 frontend via `docker compose --profile auto up`, it fails to start with the error message
`strconv.Atoi: parsing "": invalid syntax`. There is no other output from the command.

This was working fine until a few days ago. From what I can tell I think this is a docker problem so I think it stems from this repo and not AUTOMATIC1111's.

I've already tried re-cloning the repo and rebuilding the automatic frontend from scratch with `docker compose --profile auto build --no-cache` which did not help.

**Hardware / Software**
 - OS: Arch Linux
 - Kernel version: 5.15.74-1-lts
 - Docker Version: 20.10.19
 - Docker compose version: 2.12.0
 - Repo version: from master
 - RAM: 64gb
 - GPU/VRAM: 1050ti (4gb)

**Steps to Reproduce**
1. Clone this repo
2. Run `docker compose --profile auto build` (finishes without error)
3. Run `docker compose --profile auto up`

**Comment by AbdBarho** [comment]
is `strconv.Atoi: parsing "": invalid syntax` the only thing that is output? can you try with `--verbose`?
```
docker compose --verbose --profile auto up
```

Maybe we get a more meaningful error message.


Possibly  related:
https://github.com/docker/compose-cli/issues/1537
https://github.com/docker/compose/issues/9240
https://stackoverflow.com/questions/73948802/strconv-atoi-parsing-invalid-syntax#comment130813944_73948802

**Comment by loglob** [comment]
I managed to solve it:
```docker compose down --remove-orphans```
cleared some broken (?) containers and after that, it worked again.
It also deleted my model.ckpt though.

**Comment by Narimm** [comment]
Can I just say that marking this issue as complete because you found a work around is short sighted.  Clearly there is a bug in 'docker compose' that occurs in the following way:

Launch a container manually - using an image defined in a separate compose file .
Launch a compose file - which launches the same image theoretically as a new container.

Solving the problem By removing all containers NOT referenced by the docker compose file is 
1. Not solving the bug
2. Potentially giving a command out to people which could delete containers in necessary systems
