### ISSUE TITLE
Updating container to latest automatic1111 release

### ISSUE THREAD

**Issue by bluedevil678** [AbdBarho/stable-diffusion-webui-docker#169]
Do we have plans for updating the container to stay current with the updates being made by auto?

**Comment by DevilaN** [comment]
I do not believe this is a good idea.
A1111 do not have versioning incorporated, and development / progress speed is insane. Although this has numerous benefits, it also has some drawbacks, like there is no possibility to test everything. If you take a look at issues at A1111 repo, there is quite a number of bug reports stating that something has been broken by last change.
Question is whether or not we would like to be surprised from time to time by:
1. Always waiting till new version of app is build instead of just using whatever we've got right now.
2. Broken functionalities that came up from nowhere.
Probably there is a place for compromise, and with proper build params we could experimentally allow building image with "latest" version from a1111 repository, but it probably should be done on other branch and maintaining it is quite a pain in the ass.
If you are not convinced yet, then look for advices with "autoupdate on start" for original a1111 repo. There is quite a discussion if it is good or bad, but for sure this is not a 100% best thing to do.

If anything good comes up, then @AbdBarho updates this repo quite fast, so a couple of hours waiting for it to be in master branch seems like no problem at all.

**Comment by bluedevil678** [comment]
You make some valid and strong points here! A rather mature holistic view of the matter. 
On the topic of versioning a possible compromise may be for occasional docker update releases as set versions - possibly via docker hub for accessibility. 

The work done here so far is both impressive and exciting and I'd love to ensure the community stays as up to date (with this docker work) as possible.

**Comment by DevilaN** [comment]
Image on dockerhub has been discussed here: https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/7
I've got some ideas with hybrid approach, so you don't have build everything "from scratch", but there are other things to clarify first, and this is not my project, so it probably should wait a bit longer.

**Comment by AbdBarho** [comment]
I agree with all the points the @DevilaN mentioned, I could live without versioning, assuming there were tests...

IMHO, invoke / lstein is the only fork that does it right (that I know of).

Anyway I did an update in #171, maybe now you can use what you're looking for.

That being said, if you want to live on the edge and you want to try the latest state of the app without waiting for me, you can change the commit sha used for build, for example: add this to your `docker-compose.override.yml` (or create one if you don't have):

```yml
services:
  auto:
    build:
      args:
        # commit sha of the repo: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commits/master
        SHA: "df0a1f83815c771246a7b1bca85d63feaefad8d1" 
```

**Comment by MrDj200** [comment]
would I just need to put the `docker-compose.override.yml` right next to the main `docker-compose.yml`?
