### ISSUE TITLE
Scripts in /scripts don't appear in the UI

### ISSUE THREAD

**Issue by ryanbrackney** [AbdBarho/stable-diffusion-webui-docker#186]
**Has this issue been opened before?**

- [X ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

I've tried to put several scripts in the /scripts folder, but none of them show up in the UI.  

I have the following set in my  `docker-compose.override.yml`:

`services:
   auto:
     environment:
       - CLI_ARGS=--allow-code --administrator --xformers
`

Scripts tried:
https://github.com/some9000/StylePile/blob/main/StylePile.py
https://github.com/arcanite24/img2tiles/blob/master/img2tiles.py

**Which UI**
AUTO

**Hardware / Software**
 - OS: Windows 11
 - OS version: 21H2 OS Build 22000.1098
  - WSL version (if applicable): 2
 - Docker Version: 4.13.0 (89412) 
 - Docker compose version: v2.12.0
 - Repo version:  from master today,  4464e9d9e99147dcf0785d8bd0a15172b5792668
 - RAM: 32 GB
 - GPU/VRAM: 12 GB

**Steps to Reproduce**
Load docker? 

**Additional context**
I can't think of more

**Comment by dbroesch** [comment]
I'm unable to see the script in my drop down as well after container restart

**Comment by AbdBarho** [comment]
The scripts folder you are mentioning has nothing to do with the container, I have created #187 with scripts support. Pull from latest master, put your scripts in `data/config/auto/scripts`, and restart the container.

the scripts folder is NOT mounted because that would overwrite the originals scripts, you have to restart the container if you update your scripts.


| | |  |
|---|---|---|
| ![download](https://user-images.githubusercontent.com/24505302/198869347-5e9e1d07-c8ae-44ea-b46d-326327236c20.png) | ![00002-1534736652-clockwork machine library fog smoke detailed 4k fantasy vivid colors](https://user-images.githubusercontent.com/24505302/198869431-ac11fc4c-8fc2-4981-b26b-2cbfb133701a.jpg) | ![00003-1347659559-a digital illustration of clockwork machines fantasy vivid colors artstation (1)](https://user-images.githubusercontent.com/24505302/198869920-36360217-f943-482d-bc9f-891ab49011d4.jpg) |

**Comment by ryanbrackney** [comment]
thank you! You're an incredible contributor to this community!
