### ISSUE TITLE
How to remove a web-ui

### ISSUE THREAD

**Issue by newptcai** [AbdBarho/stable-diffusion-webui-docker#188]
Let's say I don't want to use `auto` anymore. How can I safely delete it and release space on my hard drive.

**Comment by AbdBarho** [comment]
you can use [docker image rm](https://docs.docker.com/engine/reference/commandline/image_rm/) and if you want to clean everything you can use [docker image prune](https://docs.docker.com/engine/reference/commandline/image_prune/)

**Comment by DevilaN** [comment]
It is not so simple as it seems.
This requires some docker knowledge and training in using docker properly is beyond scope of this post as it takes quite a good amount of time and there are plenty of info online.

First of all you can view what's takings space with `docker system df`.
You need to remove associated container(s) first, because docker will not allow you to remove images that are being used by any container (even stopped ones).

`docker container ls -a` will show containers and you decide which ones to remove.
`docker rm CONTAINER_ID` removes container
`docker image ls` shows images
`docker image rm IMAGE_ID` removes image

after deleting containers and images there is still place taken by volumes (but for automatic there are no docker volumes thou), and build cache.

If you really are lazy and don't want to dig into docker deeply, than I suggest to clean up everthing and start almost from scratch by issuing `docker system prune -a` command to delete everything dangling (read https://docs.docker.com/engine/reference/commandline/system_prune/ for detailed info). If you do this while running hlky or other service, than it should leave you with only hlky / other service files intact.
Keep on mind, that this will remove also other services / images / volumes / build cache so if you use docker for other things then this is probably not a good idea to prune entire docker system.
