### ISSUE TITLE
Not able to build dockerfile of automatic (build error unkown insturction: CAT)

### ISSUE THREAD

**Issue by barshag** [AbdBarho/stable-diffusion-webui-docker#276]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [ X] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

Tried to  run the Dockerfile of automatic1111, but got build errors:

``` dockerfile parse error line 8:  unknown instruction: CAT```

**Which UI**

auto 

**Hardware / Software**

- OS: Ubuntu 20.04
**Steps to Reproduce**
docker build . -t

**Additional context**

I went straight to dockerfile without the docker compose (cause In my platform I cannot add docker compose (runpod)) - I use theirs.

And  wanted to say thanks for this REPO!!!! :)

**Comment by AbdBarho** [comment]
@barshag what version of docker / docker compose do you have?

**Comment by barshag** [comment]
docker version 20.10.17 (for the build)
(i typed ```docker version```)

the compose is in runpod

**Comment by AbdBarho** [comment]
@barshag please not that this repo was intended to be built and run with docker compose only.

for your problem: can you try
```
docker pull docker/dockerfile:latest

DOCKER_BUILDKIT=1 docker build .
```

**Comment by barshag** [comment]
Yea. That's solve the build problem ( to make it to work is a different story :)). Thanks about  the BuildKit flag - I wasn't aware of it before! 

The issue is close for me, but I wonder why did you pull dockerfile:latest. I would like some explanation on that (to expand my knowledge on docker..)

**Comment by AbdBarho** [comment]
@barshag gladly!

[Docker buildkit](https://docs.docker.com/build/buildkit/) is a relatively new-ish build backend for docker that has a lot of features. It is activated per default in newer docker versions, but requires the env flag in older ones.

One of the features of buildkit is ability to choose a build frontend (or another syntax for the dockerfile), you can specify which syntax you want to  use as a comment in the beginning of the dockerfile:
https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/78c90e543599b04ba51d38fc9696775a63f4a0f7/services/AUTOMATIC1111/Dockerfile#L1

I mainly use the newer syntax for [heredoc](https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/) style run commands:

https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/78c90e543599b04ba51d38fc9696775a63f4a0f7/services/AUTOMATIC1111/Dockerfile#L7-L11

Now, in your case, since buildkit was not active, docker detected line 8 as a command instead of a part of the previous `RUN`. That is why it said `dockerfile parse error line 8:  unknown instruction: CAT`

The thing is, this alternative syntax by itself is really only just another docker image, although docker pulls the latest syntax image automatically on build if I am not mistaken, manually pulling `docker/dockerfile:latest` ensures you have the latest.


I hope this was a good explanation.

**Comment by barshag** [comment]
Wow! You open for me a new universe with those references - building docker-file with the expressiveness of scripting are game-changer !
Sorry about the delay in producing the  comment, but I totally appreciate your time and efforts to  educate me in this field =)
