### ISSUE TITLE
OCI Compliant Dockerfiles

### ISSUE THREAD

**Issue by ghzgod** [AbdBarho/stable-diffusion-webui-docker#352]
**Has this issue been opened before?**

- [ ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [X ] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

When I build the Dockerfile I get an errors with multiline commands containing  `<<EOF`.  This can be fixed by replacing 
the RUN commands

**Which UI**

auto

**Hardware / Software**

- OS: Ubuntu 22.0.4 / Slackware too
- Docker Version: 20.10.18
- Repo version: master
- RAM:
- GPU/VRAM:

Below is the fix for the auto Dockerfile so you can build from source.   If you implement the changes, please test it first!

```
# syntax=docker/dockerfile:1

FROM alpine/git:2.36.2 as download

SHELL ["/bin/sh", "-ceuxo", "pipefail"]

RUN \
  echo "mkdir -p repositories/\$1 && cd repositories/\$1 && git init && git remote add origin \$2 && git fetch origin \$3 --depth=1 && git reset --hard \$3 && rm -rf .git" > /clone.sh && \
  chmod +x /clone.sh

RUN \
  echo "mkdir -p repositories/\$1 && cd repositories/\$1 && git init && git remote add origin \$2 && git fetch origin \$3 --depth=1 && git reset --hard \$3 && rm -rf .git" > /clone.sh && \
  chmod +x /clone.sh

RUN . /clone.sh taming-transformers https://github.com/CompVis/taming-transformers.git 24268930bf1dce879235a7fddd0b2355b84d7ea6 \
  && rm -rf data assets **/*.ipynb

RUN . /clone.sh stable-diffusion-stability-ai https://github.com/Stability-AI/stablediffusion.git 47b6b607fdd31875c9279cd2f4f16b92e4ea958e \
  && rm -rf assets data/**/*.png data/**/*.jpg data/**/*.gif

RUN . /clone.sh CodeFormer https://github.com/sczhou/CodeFormer.git c5b4593074ba6214284d6acd5f1719b6c5d739af \
  && rm -rf assets inputs

RUN . /clone.sh BLIP https://github.com/salesforce/BLIP.git 48211a1594f1321b00f14c9f7a5b4813144b2fb9
RUN . /clone.sh k-diffusion https://github.com/crowsonkb/k-diffusion.git 5b3af030dd83e0297272d861c19477735d0317ec
RUN . /clone.sh clip-interrogator https://github.com/pharmapsychotic/clip-interrogator 2486589f24165c8e3b303f84e9dbbea318df83e8


FROM alpine:3.17 as xformers
RUN apk add --no-cache aria2
RUN aria2c -x 5 --dir / --out wheel.whl 'https://github.com/AbdBarho/stable-diffusion-webui-docker/releases/download/5.0.0/xformers-0.0.17.dev449-cp310-cp310-manylinux2014_x86_64.whl'

FROM python:3.10.9-slim

SHELL ["/bin/bash", "-ceuxo", "pipefail"]

ENV DEBIAN_FRONTEND=noninteractive PIP_PREFER_BINARY=1

RUN PIP_NO_CACHE_DIR=1 pip install torch==1.13.1+cu117 torchvision --extra-index-url https://download.pytorch.org/whl/cu117

RUN apt-get update && apt install fonts-dejavu-core rsync git jq moreutils -y && apt-get clean

RUN mkdir -p /root/.cache/pip && \
    git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git && \
    cd stable-diffusion-webui && \
    git reset --hard d7aec59c4eb02f723b3d55c6f927a42e97acd679 && \
    pip install -r requirements_versions.txt

RUN --mount=type=cache,target=/root/.cache/pip  \
  --mount=type=bind,from=xformers,source=/wheel.whl,target=/xformers-0.0.15-cp310-cp310-linux_x86_64.whl \
  pip install triton /xformers-0.0.15-cp310-cp310-linux_x86_64.whl

ENV ROOT=/stable-diffusion-webui


COPY --from=download /git/ ${ROOT}
RUN mkdir ${ROOT}/interrogate && cp ${ROOT}/repositories/clip-interrogator/data/* ${ROOT}/interrogate
RUN --mount=type=cache,target=/root/.cache/pip \
  pip install -r ${ROOT}/repositories/CodeFormer/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
  pip install pyngrok \
  git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 \
  git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 \
  git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b

# Note: don't update the sha of previous versions because the install will take forever
# instead, update the repo state in a later step

# TODO: either remove if fixed in A1111 (unlikely) or move to the top with other apt stuff
RUN apt-get -y install libgoogle-perftools-dev && apt-get clean
ENV LD_PRELOAD=libtcmalloc.so

ARG SHA=0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
RUN --mount=type=cache,target=/root/.cache/pip sh -c 'git fetch && git reset --hard ${SHA} && pip install -r requirements_versions.txt'
WORKDIR /stable-diffusion-webui

RUN --mount=type=cache,target=/root/.cache/pip  pip install -U opencv-python-headless

COPY . /docker

RUN python3 /docker/info.py ${ROOT}/modules/ui.py && \
    mv ${ROOT}/style.css ${ROOT}/user.css && \
    sed -i 's/in_app_dir = .*/in_app_dir = True/g' /usr/local/lib/python3.10/site-packages/gradio/routes.py

WORKDIR ${ROOT}
ENV CLI_ARGS=""
EXPOSE 7860
ENTRYPOINT ["/docker/entrypoint.sh"]
CMD python -u webui.py --listen --port 7860 ${CLI_ARGS}
```

**Comment by RedTopper** [comment]
This would be helpful for me as well! I have my own fork with the heredoc blocks converted to the style above so Podman's builder can work properly. But I wasn't sure if the heredoc blocks were just a podman issue, so I didn't bother to open an issue about it (this is a docker implementation, after all).

**Comment by AbdBarho** [comment]
@RedTopper Is this the only thing required to make the repo compatible with podman / buildah?

**Comment by RedTopper** [comment]
@AbdBarho Not quite. In addition to the above issue, I found the following changes were needed:

* Podman Compose doesn't (yet?) support --profile, so you either have to bodge together the usage of docker-compose (the old one, which complicates things), or remove all the other profiles before using `podman-compose up`. I'm fine doing that myself though.
* OCI images don't support `SHELL ["/bin/sh", "-ceuxo", "pipefail"]` (well, specifically `SHELL`), so you have to remove those

I'm using fedora, so `selinux` adds some additional complications with nvidia:

* I had to mount the caches with :z otherwise `pip` will fail to read the packages with "file not found"
  * This is the only one I'm not sure how docker would handle if you added that. It might throw a fit.
* selinux/rootless podman requires `security_opt: - label=type:nvidia_container_t` to access the GPU
* selinux/podman also requires the following environment variables: 
  *  `- NVIDIA_DRIVER_CAPABILITIES=compute,utility`
  *   `- NVIDIA_VISIBLE_DEVICES=all`

I've had a little playground over at [RedTopper/Stable-Diffusion-Webui-Podman](https://github.com/RedTopper/Stable-Diffusion-Webui-Podman). If you diff that repo with yours (minus my changes to the README.md, which explain some of these pitfalls), you'll see what I mean. 

Just adding what @ghzgod above suggested will reduce that amount of merge conflicts I get if I pull in any updates you have though!

**Comment by RedTopper** [comment]
@AbdBarho, would it be easier if I made a PR with just the changes @ghzgod proposes (and possibly the SHELL too)?

**Comment by AbdBarho** [comment]
Hi @RedTopper, sorry for late answer.

I would have said yes, but this would only downgrade the dockerfile with no benefits.. I was hoping that only updating the dockerfile would be enough to support podman, it seems to be much more involved than I expected, and I won't be able to maintain it.

But it looks like you already did most of the work, which I think is great. You can continue maintaining the podman variant if you want to, I can also add a link in the wiki to your fork if you intend on keeping it alive long term.

Maybe it some point in the future if there is high demand & contributer who can support it, we can add podman as a first class citizen.

**Comment by RedTopper** [comment]
Yeah, I originally didn't open a PR because I don't want to burden you with supporting extra tooling!

But I think the minimal set of changes that would be compatible with both Docker and Podman would JUST be to remove the heredoc style strings. Podman only throws a warning saying SHELL is not OCI compliant and plows along anyway.

I am certainly willing to be that contributor to help support it though! So as long as you are up for it I can split out some of the changes from my fork into minimal PRs you can accept or reject. The rest of the SELinux changes I can document in a Wiki page for you if you'd think that would be a better route.

**Comment by RedTopper** [comment]
@ghzgod, hopefully my comments would still meet your needs. I kind of intruded pretty hard on your issue here, if I end up making a PR would you be able to test it works for you too?

@AbdBarho would it still be reasonable for me to complete that work, given the above?

**Comment by AbdBarho** [comment]
@RedTopper we should think about this a bit more generally:

* we have 3 dockerfiles, ideally, all of them should be migrated (that being said, I intend on removing one of them)
* if we are going to change the dockerfile anyway, might as well make it so that it is compatible with as many build tools as possible. Unfortunately, I only know docker, and heard of podman / buildah, I was hoping maybe you have some more knowledge on what tools are there and what requirements are needed to support them? Does LXC fit anywhere near what we have here?
* All of this should be validated in the CI
* heredoc syntax & shell commands were very useful for debugging and avoiding a ton of `&& \` everywhere, also, BuildKit for parallel builds makes so much sense, are these features available in other tools, or are there any alternatives?

**Comment by RedTopper** [comment]
@AbdBarho 

* Yeah, I can migrate, build, and test them all locally no problem.

* Funnily enough, I learned all the quirks and behaviors of Podman/Buildah through trying to get your repository working on Fedora. I still use Docker on another server, but I don't build containers there, only download and deploy them.

* This would probably be accomplished with `redhat-actions/buildah-build@v2`, but I haven't set up CI on GitHub before (only Azure). Not sure if I would be the best of help there :disappointed: 

* As for the heredoc syntax, would it be possible to pull out some of the commands from the Dockerfiles itself and drop them into .sh scripts with the appropriate fail-early flags set and a `COPY` into the container?

**Comment by RedTopper** [comment]
@AbdBarho I should mention I'm still willing to work on this, but I wanted to make sure you were ok with above before I started

**Comment by AbdBarho** [comment]
@RedTopper Hey, thank you, I am unfortunately still busy, we will do a release of the dataset of Open-assistant repo within the next weeks, so time is still tight.

I haven't forgotten, I will get back to you.

Since you are already here, maybe you would like to give our chat bot a try?

https://open-assistant.io/chat

https://github.com/LAION-AI/Open-Assistant

**Comment by AbdBarho** [comment]
@RedTopper maybe I can try to fit this into my schedule now, if you have some stuff already, could you open a PR?

It does not have to be everything, what ever you have.

**Comment by RedTopper** [comment]
Ope, yes, of course! Let me collect that.

**Comment by RedTopper** [comment]
@ghzgod Since you are the original issue creator, could you try out my changes too? You can clone https://github.com/RedTopper/Stable-Diffusion-Webui-Podman/tree/oci-docker, and `git checkout oci-docker`

**Comment by AbdBarho** [comment]
Can we consider this closed for now?

**Comment by RedTopper** [comment]
@AbdBarho I'd say so!

Does having the proper runtime/security_opt in the docker-compose still interest you? Those options are almost specifically for Fedora/SELinux users using Podman (and I suspect what #389 is running into). I have a feeling that those who are adventurous enough to use a tool like Podman are probably willing to uncomment a couple lines in a docker-compose in order to get a setup working.

It could also best be written in documentation too. I'll leave the decision up to you though, just @ mention me.

**Comment by AbdBarho** [comment]
@RedTopper I would prefer if we have it in the docs. Users can create a `docker-compose.override.yml` and put the new stuff there.

Another reason why I don't want comments in the main files is that every time we update, and the user wants to git pull, they would have merge conflicts, which is no fun.

Maybe you can write the stuff here and I can copy it there, if it is too much I would have to see how to give you write access to the wiki.

**Comment by RedTopper** [comment]
Yes, very good point. I was looking into using `docker-compose.override.yml` (a `podman-compose.yml` next to a `docker-compose.yml` actually gets merged the exact same way) a few days ago and came up with this: https://github.com/RedTopper/Stable-Diffusion-Webui-Podman/blob/podman/podman-compose.yml, but it only works in podman compose 1.0.7...

Here's the manual instructions, along with explinations of why these changes are needed:

On an selinux machine like Fedora, append `:z` to the volume mounts. This tells selinux that the files are shared between containers (required for download and your UI of choice to access the same files). *Properly merging :z with an override will work in podman compose 1.0.7, specifically commit https://github.com/containers/podman-compose/commit/0b853f29f44b846bee749e7ae9a5b42679f2649f*

```yaml
x-base_service: &base_service
    volumes:
      - &v1 ./data:/data:z
      - &v2 ./output:/output:z
```

You'll also need to add the runtime and security opts to allow access to your GPU. This can be specified in an override, no new versions required! More information can be found at this RedHat post: [How to enable NVIDIA GPUs in containers](https://www.redhat.com/en/blog/how-use-gpus-containers-bare-metal-rhel-8).

```yaml
x-base_service: &base_service
    ...
    runtime: nvidia
    security_opt:
      - label=type:nvidia_container_t
```

I also had to add `,Z` to the pip/apt caches for them to work. On the first build everything will be fine without the fix, but on the second+ build, you may get a "file not found" when pip goes to install a package from the cache. Here's a script to do this easily, along with more info: https://github.com/RedTopper/Stable-Diffusion-Webui-Podman/blob/podman/selinux-cache.sh.

Lastly, delete all the services you don't want to use. *Using `--profile` will work in podman compose 1.0.7, specifically commit https://github.com/containers/podman-compose/commit/8d8df0bc2816d8e8fa142781d9018a06fe0d08ed*

Hopefully this gives folks enough information to use rootless podman.

**Comment by AbdBarho** [comment]
I have updated the wiki, thank you for your contribution! ♥

https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/Podman-Support
