### ISSUE TITLE
Issue #21 is back: Execution bit lost on /docker/mount.sh

### ISSUE THREAD

**Issue by hughk** [AbdBarho/stable-diffusion-webui-docker#36]
Building the container works. Starting the container fails (again) with the following message:

stable-diffusion-webui-docker-model-1 | + /docker/mount.sh
stable-diffusion-webui-docker-model-1 | /bin/bash: line 1: /docker/mount.sh: Permission denied

Steps to Reproduce

    docker compose build
    docker compose up --build
    [error...]

Hardware / Software:

    OS: Windows 11/WSL2
    Docker version
    GPU: [Nvidia 3090]
    Docker version: v20.10.17

Additional context
Attempted to add a chmod +x /docker/mount.sh before the command is run in dockerfile, the command does execute but does not improve things. Docker seems to work otherwise. A different version seems to have been deployed.

**Comment by AbdBarho** [comment]
@hughk can you update the command from `/docker/mount.sh` to `/bin/bash -c /docker/mount.sh`?

**Comment by AbdBarho** [comment]
I have updated the executable status again, I have to find a permanent solution for this problem...

**Comment by hughk** [comment]
So I stashed my stuff and git pulled again. I chmoded the copy of mount.sh both in hlkm and in the AUTOMATIC1111 sub-directories checked the execute bit was on, It was and tried again. Same problem. I'm unsure though exactly what is happening as we now have two Dockerfiles. So Im not quite sure which is causing the problem.

**Comment by hughk** [comment]
@AbdBarho Complete delete of local depository (except for models) and GIT pull seems to work

**Comment by AbdBarho** [comment]
@hughk glad it was fixed, since it is the second you had this problem, maybe it is a problem with git config, can you run this for the future?

```
git config --global core.fileMode true
```
Info from the git docs:

core.fileMode
  Tells Git if the executable bit of files in the working tree is to be honored.


  
  Some filesystems lose the executable bit when a file that is marked as executable is checked out, or checks out a non-executable file with executable bit on. [git-clone(1)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-clone.html) or [git-init(1)](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-init.html) probe the filesystem to see if it handles the executable bit correctly and this variable is automatically set as necessary.
