### ISSUE TITLE
Updating automatic1111

### ISSUE THREAD

**Issue by galoi9** [AbdBarho/stable-diffusion-webui-docker#373]
Could you update the documentation the best process to update the components?

**Comment by AbdBarho** [comment]
https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/169#issuecomment-1289459468

The process is the same for all others.

That being said, you as a user should in theory not be responsible for this, since there might be other changes required in the container and mounting setup for it to work.


In any case, auto1111 did not get an update since about a week, and this repo already has the latest version.

**Comment by galoi9** [comment]
thanks for the info
