### ISSUE TITLE
safetensors instead of ckpt ?

### ISSUE THREAD

**Issue by simonmcnair** [AbdBarho/stable-diffusion-webui-docker#504]
Just out of curiosity, I am aware that ckpt can contain viruses vs safetensor which can't.  Is there a reason why the ckpt is used ?  Is it because on of the other interfaces does not support safetensor ?  If that is the case can you download the safetensor for A1111 and not the others ?

Just a request please, just curious

**Comment by DevilaN** [comment]
Discussion request rather than issue.

**Comment by AbdBarho** [comment]
> Is there a reason why the ckpt is used ?

When this repository was first started, there were no safetensors.

I think I started in August, and safetensors started around September, stable diffusion safetensors were added in February, and it took a while until A1111 got support, but I never bothered to change because the models are safe and their SHAs are checked.

**Comment by alxpettit** [comment]
You should add safe tensors please. There will be more models coming out :)

**Comment by AbdBarho** [comment]
Sure, when I add more models here they will be safetensors

**Comment by alxpettit** [comment]
this should be closed as completed -- not 'not planned'.
