### ISSUE TITLE
Invoke build exits with error code 1 - known torchmetrics version mismatch

### ISSUE THREAD

**Issue by willcitizen** [AbdBarho/stable-diffusion-webui-docker#553]
**I dont believe this is previously reported here**

- [x ] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

**Which UI**

invoke

**Hardware / Software**

- OS: [Windows 11 Pro]

**Steps to Reproduce**

1. sudo docker compose --profile invoke up --build

**Additional context**

https://github.com/invoke-ai/InvokeAI/issues/3658
https://github.com/invoke-ai/InvokeAI/issues/3700

**Comment by AbdBarho** [comment]
should be solved after 3.0.0 upgrade
https://github.com/invoke-ai/InvokeAI/releases/tag/v3.0.0

hopefully I will come to it soon

**Comment by Ravius** [comment]
Hello, same issue. 
is it fixed? 
Should i just comment git reset --hard?

**Comment by kelvinRide** [comment]
> Hello, same issue. is it fixed? Should i just comment git reset --hard?

check the pr related to this issue or look at this issue here:
 https://github.com/AbdBarho/stable-diffusion-webui-docker/issues/540
 
 adding the below after line 35  worked for me but it's a temp fix:
RUN --mount=type=cache,target=/root/.cache/pip \
  pip uninstall -y torchmetrics && \
  pip install torchmetrics==0.11.4

**Comment by AbdBarho** [comment]
#596
