### ISSUE TITLE
Cannot open the image output path in wsl2 docker container！！！

### ISSUE THREAD

**Issue by RedHeartSecretMan** [AbdBarho/stable-diffusion-webui-docker#566]
**Has this issue been opened before?**

- [x] It is not in the [FAQ](https://github.com/AbdBarho/stable-diffusion-webui-docker/wiki/FAQ), I checked.
- [x] It is not in the [issues](https://github.com/AbdBarho/stable-diffusion-webui-docker/issues?q=), I searched.

**Describe the bug**

The problem, as stated in the title, is that I have successfully built the auto image and started the container in the WSL2 environment. All computational processes are working fine. However, the functionality to open the output image folder in the web UI is not working. When I click the folder icon to open it, the following error occurs.

```bash
.
.
.
...
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui_common.py", line 151, in <lambda>
webui-docker-auto-1  |     fn=lambda: open_folder(shared.opts.outdir_samples or outdir),
webui-docker-auto-1  |   File "/stable-diffusion-webui/modules/ui_common.py", line 131, in open_folder
webui-docker-auto-1  |     sp.Popen(["wsl-open", path])
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
webui-docker-auto-1  |     self._execute_child(args, executable, preexec_fn, close_fds,
webui-docker-auto-1  |   File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
webui-docker-auto-1  |     raise child_exception_type(errno_num, err_msg, err_filename)
webui-docker-auto-1  | FileNotFoundError: [Errno 2] No such file or directory: 'wsl-open'
```

The error occurs at line 131 of "https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/ui_common.py", specifically at the command "`sp.Popen(["wsl-open", path])`". This line of code seems to be attempting to use a command called "wsl-open" to open a specific path. After understanding the problem, I attempted to resolve it and made the following attempts:

First, I executed "`docker exec -it afa7e0698718 bash`" to enter the container based on the inherited "auto" image. I tried running "`wsl-open`" but encountered an error:

```bash
root@afa7e0698718:/stable-diffusion-webui# wsl-open
bash: wsl-open: command not found
```

Then, I proceeded to download the script "https://github.com/4U6U57/wsl-open/blob/master/wsl-open.sh" and added it to the bash environment inside the container. At this point, the system recognized the "`wsl-open`" command, but I still encountered the same error.

Subsequently, I installed the "`wsl-open`" script command inside WSL2, and it worked correctly, allowing me to open folders. However, when I manually executed the "`wsl-open path`" command within the Docker container in WSL2, I encountered the following errors:

```bash
bin   data  docker  home  lib64  mnt  output  root  sbin  stable-diffusion-webui  tmp  var
boot  dev   etc     lib   media  opt  proc    run   srv   sys                     usr
root@afa7e0698718:/# wsl-open data
wsl-open: ERROR: Directory not in Windows partition: /data
root@afa7e0698718:/# wsl-open /mnt/c
wsl-open: ERROR: File/directory does not exist: /mnt/c
```

**Which UI**

auto

**Hardware / Software**

- OS: Windows 11 / Ubuntu 22.04
- OS version: 22H2
- WSL version (if applicable): 2（5.15.90.1-microsoft-standard-WSL2）
- Docker Version: 24.0.4
- Docker compose version: v2.20.2
- Repo version: 8.1.0
- RAM: 32GB
- GPU/VRAM: 16GB

**Steps to Reproduce**

1. Go to ' docker compose --profile auto up'
2. Click on 'open images output directory'
3. See error

**Additional context**
Any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by AbdBarho** [comment]
This is expected, because everything is running inside a container, there is no access to the host and this feature won't work.

Of course you can try to find workarounds, but this goes against the "principles" of containerization.

It should work if you run without the container, by installing directly from A1111 repo.

**Comment by trevorbicewebdesign** [comment]
I am also running into this on a Windows 10 machine with WSL 2 installed and am seeing the same issue of not being able to open saved images from the Automatic1111 UI.  Not having this feature isn't necessarily a deal breaker, but it sure would be nice to not have to manually re-enter all your settings to open a saved image. @AbdBarho I really appreciate all the work you put into this.

**Comment by DevilaN** [comment]
Running in docker is like running on other machine. You cannot open files from other machine from your browser without additional support for file sharing over network.
A1111 just implemented calling a process to open locally some directory, but this does not work when accessing over network.

If you are running A1111 instance on your local machine instead of clicking icon in Auto interface you can just add shortcut to proper directory in your filesystem where output images are stored.

If you are running A1111 remotely or just want another way of accessing / interacting with images via WebUI, then there is solution for this in form of following extension: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser
After installing it you can browse / download / manage images via "Image Browser" tab in WebUI.
