### ISSUE TITLE
Please add support to upload textual inversion embedding

### ISSUE THREAD

**Issue by sausax** [AbdBarho/stable-diffusion-webui-docker#6]
Please add changes required to support upload of textual inversion embeddings as mentioned here: https://github.com/hlky/sd-enable-textual-inversion

**Comment by AbdBarho** [comment]
I will give it a look today after work!

**Comment by AbdBarho** [comment]
@sausax Unfortunately, the UI in its latest version does not seems to provide a file upload for the pre-made embedding, [unlike what is mentioned here](https://github.com/hlky/sd-enable-textual-inversion#how-to-use), or at least I could not find it, therefore I cannot implement / test this feature.

if you know where I can find it that would be great! otherwise I would suggest you get in contact with author of the library, either here https://github.com/hlky/sd-enable-textual-inversion or here https://github.com/hlky/stable-diffusion

**Comment by sausax** [comment]
This is weird. The code is present here in the original repo: https://github.com/hlky/stable-diffusion-webui/blob/master/frontend/frontend.py#L99 

But it is not coming up in the ui by the docker container.

**Comment by AbdBarho** [comment]
The model needs to have the an [`embedding_manager` attribute](https://github.com/hlky/stable-diffusion-webui/blob/master/webui.py#L1583), which seems to be done [here](https://github.com/hlky/sd-enable-textual-inversion/blob/main/ldm/models/diffusion/ddpm.py#L488), However, the `LatentDiffusion` class is NOT instantiated in the [WebUI](https://github.com/hlky/stable-diffusion-webui/blob/master/webui.py).

**Comment by fpgaminer** [comment]
https://github.com/hlky/sd-enable-textual-inversion/blob/08f9b5046552d17cf7327b30a98410222741b070/configs/stable-diffusion/v1-inference.yaml#L20

The sd-enable repo also has a modified config, which includes a `personalization_config` key.  Does that perhaps get the WebUI to change its behavior?

**Comment by AbdBarho** [comment]
@fpgaminer it might be that [`cp -rf` that I used](https://github.com/AbdBarho/stable-diffusion-webui-docker/blob/19f940207622ed82d887289aa53b88713b6094f3/build/Dockerfile#L34) is not enough, I will dig deeper!

**Comment by AbdBarho** [comment]
I have made sure that the the new configuration is included. In the attached log you can see that the `personalization_config` is part of main repo.

[log.txt](https://github.com/AbdBarho/stable-diffusion-webui-docker/files/9456534/log.txt)

Yet still, I can't see anything new in the UI
![localhost_7860_](https://user-images.githubusercontent.com/24505302/187540068-fcf10063-6a88-4c1e-87d7-0e3106f45aee.png)

This is the code I used in the dockerfile to copy the stuff over, feel fee to experiment with it
```dockerfile
RUN apt-get update && apt install rsync -y && apt-get clean
RUN git clone https://github.com/hlky/sd-enable-textual-inversion.git && cd sd-enable-textual-inversion && \
git reset --hard 08f9b5046552d17cf7327b30a98410222741b070
RUN rsync -a /sd-enable-textual-inversion/ /stable-diffusion/
RUN cat /stable-diffusion/configs/stable-diffusion/v1-inference.yaml

```

**Comment by fpgaminer** [comment]
Remove the `--optimized` and `--optimized-turbo` flags and the UI will show:

<img width="784" alt="Screen Shot 2022-08-30 at 3 59 22 PM" src="https://user-images.githubusercontent.com/1585817/187558102-ad35e079-b0ef-4541-b6bb-b50e552f94f1.png">

**Comment by fpgaminer** [comment]
Okay, got it fully working. Also need to add the `--no-half` flag, otherwise it errors out during generation.  Tested using my own embedding.  FYI, textual inversion doesn't work great for SD right now anyway.  I think they have it tweaked for plain Latent Diffusion, not the specific Stable Diffusion model.  So we'll need to wait for another update there to get better results.

<img width="1587" alt="Screen Shot 2022-08-30 at 4 07 33 PM" src="https://user-images.githubusercontent.com/1585817/187558987-0df74a45-b63d-4d18-85ef-a3799e7d7df8.png">

**Comment by sausax** [comment]
@fpgaminer can you create a PR with the fix ?

**Comment by AbdBarho** [comment]
Thanks @fpgaminer I managed to get it up and running with the correct cli args, I also updated the Readme.


@sausax Can you try from again with version `0.1.0`?

**Comment by sausax** [comment]
@AbdBarho Getting a new error when trying to build the latest master 

> $ docker-compose build
> Building model
> Sending build context to Docker daemon  9.216kB
> Error response from daemon: dockerfile parse error line 33: unknown instruction: GIT
> ERROR: Service 'model' failed to build : Build failed

**Comment by AbdBarho** [comment]
@sausax can you try again with `docker compose` instead of `docker-compose`? one of them is v1 the other one is v2.

I am using Heredoc syntax which is modern feature, you need a relatively modern docker version (from the last half year or so)

**Comment by sausax** [comment]
That worked :) Thanks @AbdBarho
