### ISSUE TITLE
network_mode should be set to "host"

### ISSUE THREAD

**Issue by fiesh** [AbdBarho/stable-diffusion-webui-docker#606]
I accidentally filed this in the wrong project... see https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13623

### What happened?

Our iptables policy for chain INPUT is set to DROP. This means that without setting network_mode to host in docker-compose.yml, ingress traffic to the container is blocked by it.

I don't think there's any downside to setting it to host, so I think this would be an improvement in general.

### Steps to reproduce the problem

Set iptables -P INPUT DROP, start docker compose --profile auto-cpu up --build, try curl http://localhost:7860, and observe nothing ever happens since the packets are filtered.
What should have happened?

Firewall should have been opened by docker.

### Sysinfo

Docker version 24.0.5, build ced0996600

**Comment by DevilaN** [comment]
Isn't it a docker issue rather than this project?
Host network mode means I cannot override ports exposed by this app as it directly works on 7860. This is counterintuitive and disallows any other app to work on this port on host.

If your firewall specific solution works, just use docker-compose.override.yml to make your changes permament for your very local installation instead of forcing it for others who do not have such problem.

**Comment by fiesh** [comment]
> Isn't it a docker issue rather than this project? Host network mode means I cannot override ports exposed by this app as it directly works on 7860. This is counterintuitive and disallows any other app to work on this port on host.

Then my statement 

> I don't think there's any downside to setting it to host, so I think this would be an improvement in general.

was incorrect.  The general issue is that we configure a proper address pool for IPv4 and IPv6 via docker's `daemon.json` and then want this to be a "proper subnet," including proper firewalling.  But I agree that that's a general docker issue then, thank you for your feedback!
